### ISSUE TITLE
GitHub Actions Disabled Due to Inactivity

### ISSUE THREAD

**Issue by aitaro** [gaetschwartz/all_lint_rules#7]
I've noticed that the scheduled workflows in this repository have been disabled with the following message:

`This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.`

Could someone please help to turn the GitHub Actions back on?

**Comment by csells** [comment]
yes, please! I use this package and love it!

**Comment by gaetschwartz** [comment]
Thank you for the heads-up and sorry for the delay, re-enabled it :)
